name: my first workflow
on: push

jobs: 
  print_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello
        run: echo "Hello, World!"
      - name: Checkout repository
        uses: actions/checkout@v7
        
      - name: Read the README file
        run: cat README.md
        